In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [2]:
data=pd.read_csv('F:\\1.02. Multiple linear regression.csv')

In [3]:
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [9]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

In [5]:
x=data[['SAT','Rand 1,2,3']]
y=data['GPA']

In [23]:
x

SAT  Rand 1,2,3
0   1714           1
1   1664           3
2   1760           3
3   1685           3
4   1693           2
..   ...         ...
79  1936           3
80  1810           1
81  1987           3
82  1962           1
83  2050           2

[84 rows x 2 columns]

In [6]:
reg=LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [7]:
reg.score(x,y)         #R square

0.40668119528142815

In [8]:
reg.coef_                   #coefficient

array([ 0.00165354, -0.00826982])

In [10]:
reg.intercept_               #intercept

0.29603261264909353

# prediction



In [36]:
new_data=pd.DataFrame(data=[1740,1760],columns=['SAT'])
new_data


SAT
0  1740
1  1760

In [37]:
reg.predict(new_data)

array([3.15593751, 3.18905127])

In [38]:
new_data['predicted_GPA'] =reg.predict(new_data)
new_data


SAT  predicted_GPA
0  1740       3.155938
1  1760       3.189051

# formula for adjusted R^2
 R^2=1-(1-R^2)*(n-1)/(n-p-1)

In [14]:
r2=reg.score(x,y)

n=x.shape[0]              ## n = no. of observation =84
p=x.shape[1]              ## p= no. of predictors =2

R2_Adj= 1-(1-r2)*(n-1)/(n-p-1)
print('adjusted R square = ',R2_Adj)

adjusted R square =  0.39203134825134


# Feature selection

In [15]:
from sklearn.feature_selection import f_regression

In [17]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

it gives F stats value and p values respectivelly for SAT AND Rand 1,2,3

In [19]:
p_value=f_regression(x,y)[1]
p_value

array([7.19951844e-11, 6.76291372e-01])

In [20]:
p_value.round(3)

array([0.   , 0.676])

it shows that p value for SAT is 0 (very low) but for rand1,2,3 it is high(>0.05) so we discard rand1,2,3

# creating summary table

In [22]:
reg_summary=pd.DataFrame(data=x.columns.values,columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [24]:
reg_summary['coefficient']=reg.coef_
reg_summary['p_values']=p_value

In [25]:
reg_summary

Features  coefficient      p_values
0         SAT     0.001654  7.199518e-11
1  Rand 1,2,3    -0.008270  6.762914e-01